---
title: "Renewing GPG keys"
date: 2020-06-26T22:00:00+02:00
draft: false
tags: [gpg, ssh, pgp]
categories: ["Cibersecurity"]
languages: [en]
---

== GnuPG Renewal Day

Nearly one year after my first (and so far, lonely) post, it is time to renew
my GPG keys. Doing this just once a year make the process prone to be forgotten, 
so maki

=== My set-up

Let's first take a look at how I set-up my GPG keys. I'll also go

==== Separated Signature, Encryption and Authorization sub-keys

I use separate sub-keys for Signature, Encryption and Authorization enabled sub-keys.

Separating signature and encryption sub-keys is a typical approach because the
encryption sub-key tends to live longer than signing sub-keys. 

In fact, GnuPG tools operate as if there was only one encryption sub-key in a keypair, 
how would it otherwise know which to use when you want to encrypt a message for a certain 
recipient?

...
	gpg --encrypt -r foo@bar.com  
	# If foo@bar.com has more than one encryption sub-key, which one should be used?
... 

By extension, I opted to use also separated authentication key. This turned out
to be a good decision since at some point I had to change the authorization subkey
type from RSA to ed_25519 or otherwise it wouldn't work with bitbucket (for reasons I
don't know yet).

==== Secret sub-keys are copied to OpenPGP Smart Cards

I keep one with me and the other at home. 

==== Secret keys stored in separate removable media

The secret keys are stored in a removable media in gpg armor format and they 
are encrypted with a passphrase. I keep this media at two different geographic locations and
never take it with me.

Why did I choose to not have it in a smart card? 

== Risk evaluation

* If someone steals my secret keys back-backup at one location... I shall decide whether I believe
  they can crack the passphrase that protects them. 
* If someone steals all my secret sub-keys backup... Which require them to find them in multiple
  geographic locations, I'm still able to operate for as long as they don't steal also my Open 
  GPG Smart Cards, one of which I always bring with me.
  This would mean however that I'd need to start thinking on a new key-pair because I won't be
  able to extract the secret keys from the Smart Cards and that is a risk as I won't be able to
  generate replicated keys.




